kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: testbed-kme
nodes:
- role: control-plane
  image: kindest/node:v1.26.6
  extraPortMappings:
    - containerPort: 30001
      hostPort: 30001       
      protocol: TCP
    - containerPort: 30003
      hostPort: 30003       
      protocol: TCP
    - containerPort: 30005
      hostPort: 30005       
      protocol: TCP