---
quditto_version: 0.1.0
config:
  application_interface: etsi-gs-qkd-004
  qkd_protocol: e91
nodes:
  - node_name: qnode1
    node_ip: 10.4.32.207
    neighbour_nodes:
      - qnode2
      - qnode3

  - node_name: qnode2
    node_ip: 10.4.32.121
    neighbour_nodes:
      - qnode1
      - qnode5

  - node_name: qnode3
    node_ip: 10.4.32.106
    neighbour_nodes:
      - qnode1
      - qnode4
      - qnode5

  - node_name: qnode4
    node_ip: 10.4.32.124
    neighbour_nodes:
      - qnode3
      - qnode5
      - qnode6

  - node_name: qnode5
    node_ip: 10.4.32.107
    neighbour_nodes:
      - qnode2
      - qnode3
      - qnode4
      - qnode7

  - node_name: qnode6
    node_ip: 10.4.32.252
    neighbour_nodes:
      - qnode4
      - qnode7

  - node_name: qnode7
    node_ip: 10.4.32.153
    neighbour_nodes:
      - qnode5
      - qnode6
