apiVersion: apps/v1
kind: Deployment
metadata:
  name: qd2-kme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qd2-kme
  template:
    metadata:
      labels:
        app: qd2-kme
    spec:
      containers:
      - name: qd2-kme-container
        image: buchillo/testbed-kme-qd2:latest
        imagePullPolicy: Always
        workingDir: /usr/src/app
        securityContext:
          capabilities:
            add:
            - "NET_ADMIN"
---
apiVersion: v1
kind: Service
metadata:
  name: kme-servicio
spec:
  type: NodePort
  selector:
    app: kme
  ports:
  - name: ksid-port
    port: 65431
    targetPort: 65431
    nodePort: 30001
  - name: etekey-port
    port: 65433
    targetPort: 65433
    nodePort: 30003
  - name: httpserver-port
    port: 65435
    targetPort: 65435
    nodePort: 30005
  - name: qd2client-port
    port: 31942
    targetPort: 31942
    nodePort: 30002
