kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pqkd-testbed
nodes:
- role: control-plane
  image: kindest/node:v1.26.6
  extraPortMappings:
    - containerPort: 30006
      hostPort: 30006
      protocol: TCP
