apiVersion: apps/v1
kind: Deployment
metadata:
  name: pqkd-kme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pqkd-kme
  template:
    metadata:
      labels:
        app: pqkd-kme
    spec:
      containers:
      - name: pqkd-kme-container
        image: buchillo/testbed-kme-pqkd:latest
        imagePullPolicy: Always
        workingDir: /home/ubuntu
        securityContext:
          capabilities:
            add:
            - "NET_ADMIN"
---
apiVersion: v1
kind: Service
metadata:
  name: pqkd-kme-servicio
spec:
  type: NodePort
  selector:
    app: pqkd-kme
  ports:
  - name: pqkd-kme-port
    port: 5000
    targetPort: 5000
    nodePort: 30006
